# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 112317470+falcaozane@users.noreply.github.com
author_name: Falcao Zane Vijay
contract_name: digital_marketplace
deployment_language: python
preset_name: starter
project_name: digital_marketplace

